name: Build & Deploy Pages (tools)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p _site && cp -r * _site || true
      - run: |
          # copy generated tools/index.html from the Safe Check recipe
          # or re-run the same generation here; simplest is to re-run the python:
          python3 - << 'PY'
# (Paste the same Python generator from Safe Check here, writing to _site/tools/index.html)
PY
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: { path: '_site' }
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: { pages: write, id-token: write }
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
